import "./globals.css";
import { Inter } from "next/font/google";
import NavBar from "./components/NavBar";
import WhatsAppBtn from "./components/WhatsAppBtn";
import Footer from "./components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Abraham Climatización",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar />
        <main>{children}</main>
        <WhatsAppBtn />
        <Footer />
      </body>
    </html>
  );
}
